// Equivalencias de ingredientes para mostrar alternativas
export const EQUIVALENCIAS: Record<string, string[]> = {
  Pollo: ["Pechuga de pavo", "Tofu"],
  Res: ["Pechuga de pavo", "Pollo"],
  Pescado: ["Atún", "Tofu"],
  Huevo: ["Tofu", "Queso"],
  Tofu: ["Pollo", "Huevo"],
  Lentejas: ["Frijoles", "Quinoa"],
  Arroz: ["Quinoa", "Pasta"],
  Pasta: ["Arroz", "Quinoa"],
  Papa: ["Camote", "Calabaza"],
  Aguacate: ["Aceite de oliva", "Almendra"],
  "Aceite de oliva": ["Aguacate", "Nuez"],
  Manzana: ["Plátano", "Fresa"],
  Plátano: ["Manzana", "Mango"],
  Espinaca: ["Brócoli", "Calabaza"],
  Brócoli: ["Espinaca", "Calabaza"],
  Zanahoria: ["Calabaza", "Papa"],
  Tomate: ["Pepino", "Calabaza"],
  Queso: ["Yogur", "Huevo"],
  Yogur: ["Queso", "Leche"],
  Frijoles: ["Lentejas", "Quinoa"],
  "Pechuga de pavo": ["Pollo", "Res"],
  Atún: ["Pescado", "Pollo"],
  Quinoa: ["Arroz", "Lentejas"],
  Camote: ["Papa", "Calabaza"],
  Almendra: ["Nuez", "Aguacate"],
  Nuez: ["Almendra", "Aceite de oliva"],
  Leche: ["Yogur", "Queso"],
  Fresa: ["Manzana", "Mango"],
  Mango: ["Fresa", "Plátano"],
  Calabaza: ["Papa", "Zanahoria"],
  Pepino: ["Tomate", "Calabaza"],
  Espárrago: ["Brócoli", "Espinaca"],
  Avena: ["Quinoa", "Arroz"],
  Chía: ["Nuez", "Almendra"],
  "Yogur griego": ["Yogur", "Queso"],
};
// Listado base de alimentos y recetas para el generador de menú
export const ALIMENTOS = [
  { nombre: "Pollo", tipo: "proteína" },
  { nombre: "Res", tipo: "proteína" },
  { nombre: "Pescado", tipo: "proteína" },
  { nombre: "Huevo", tipo: "proteína" },
  { nombre: "Tofu", tipo: "proteína" },
  { nombre: "Lentejas", tipo: "carbohidrato" },
  { nombre: "Arroz", tipo: "carbohidrato" },
  { nombre: "Pasta", tipo: "carbohidrato" },
  { nombre: "Papa", tipo: "carbohidrato" },
  { nombre: "Aguacate", tipo: "grasa" },
  { nombre: "Aceite de oliva", tipo: "grasa" },
  { nombre: "Manzana", tipo: "fruta" },
  { nombre: "Plátano", tipo: "fruta" },
  { nombre: "Espinaca", tipo: "verdura" },
  { nombre: "Brócoli", tipo: "verdura" },
  { nombre: "Zanahoria", tipo: "verdura" },
  { nombre: "Tomate", tipo: "verdura" },
  { nombre: "Queso", tipo: "lácteo" },
  { nombre: "Yogur", tipo: "lácteo" },
  { nombre: "Frijoles", tipo: "carbohidrato" },
  { nombre: "Pechuga de pavo", tipo: "proteína" },
  { nombre: "Atún", tipo: "proteína" },
  { nombre: "Quinoa", tipo: "carbohidrato" },
  { nombre: "Camote", tipo: "carbohidrato" },
  { nombre: "Almendra", tipo: "grasa" },
  { nombre: "Nuez", tipo: "grasa" },
  { nombre: "Leche", tipo: "lácteo" },
  { nombre: "Fresa", tipo: "fruta" },
  { nombre: "Mango", tipo: "fruta" },
  { nombre: "Calabaza", tipo: "verdura" },
  { nombre: "Pepino", tipo: "verdura" },
  { nombre: "Espárrago", tipo: "verdura" },
  { nombre: "Avena", tipo: "carbohidrato" },
  { nombre: "Chía", tipo: "grasa" },
  { nombre: "Yogur griego", tipo: "lácteo" },
  // Más frutas
  { nombre: "Pera", tipo: "fruta" },
  { nombre: "Uva", tipo: "fruta" },
  { nombre: "Sandía", tipo: "fruta" },
  { nombre: "Melón", tipo: "fruta" },
  { nombre: "Piña", tipo: "fruta" },
  { nombre: "Durazno", tipo: "fruta" },
  { nombre: "Ciruela", tipo: "fruta" },
  { nombre: "Papaya", tipo: "fruta" },
  { nombre: "Kiwi", tipo: "fruta" },
  { nombre: "Mandarina", tipo: "fruta" },
  { nombre: "Naranja", tipo: "fruta" },
  // Más verduras
  { nombre: "Jitomate", tipo: "verdura" },
  { nombre: "Cebolla", tipo: "verdura" },
  { nombre: "Lechuga", tipo: "verdura" },
  { nombre: "Coliflor", tipo: "verdura" },
  { nombre: "Calabacita", tipo: "verdura" },
  { nombre: "Betabel", tipo: "verdura" },
  { nombre: "Champiñón", tipo: "verdura" },
  { nombre: "Apio", tipo: "verdura" },
  { nombre: "Pepitas", tipo: "grasa" },
  // Más grasas saludables
  { nombre: "Cacahuate", tipo: "grasa" },
  { nombre: "Aceituna", tipo: "grasa" },
  { nombre: "Semilla de girasol", tipo: "grasa" },
  { nombre: "Semilla de calabaza", tipo: "grasa" },
  { nombre: "Tahini", tipo: "grasa" },
  { nombre: "Mantequilla de maní", tipo: "grasa" },
  { nombre: "Coco", tipo: "grasa" },
  { nombre: "Linaza", tipo: "grasa" },
];

// Macros por 100g de cada alimento principal (aproximados)
import type { IngredientMacros } from "../types/IngredientMacros";
export const INGREDIENTES_MACROS: IngredientMacros[] = [
  { nombre: "Pollo", proteina: 22, carbohidrato: 0, grasa: 2, kcal: 110 },
  { nombre: "Res", proteina: 21, carbohidrato: 0, grasa: 8, kcal: 150 },
  { nombre: "Pescado", proteina: 20, carbohidrato: 0, grasa: 5, kcal: 120 },
  { nombre: "Huevo", proteina: 13, carbohidrato: 1, grasa: 11, kcal: 155 },
  { nombre: "Tofu", proteina: 8, carbohidrato: 2, grasa: 4, kcal: 76 },
  { nombre: "Lentejas", proteina: 9, carbohidrato: 20, grasa: 0.4, kcal: 116 },
  { nombre: "Arroz", proteina: 2.7, carbohidrato: 28, grasa: 0.3, kcal: 130 },
  { nombre: "Pasta", proteina: 5, carbohidrato: 25, grasa: 1, kcal: 130 },
  { nombre: "Papa", proteina: 2, carbohidrato: 17, grasa: 0.1, kcal: 77 },
  { nombre: "Aguacate", proteina: 2, carbohidrato: 9, grasa: 15, kcal: 160 },
  {
    nombre: "Aceite de oliva",
    proteina: 0,
    carbohidrato: 0,
    grasa: 100,
    kcal: 900,
  },
  { nombre: "Manzana", proteina: 0.3, carbohidrato: 14, grasa: 0.2, kcal: 52 },
  { nombre: "Plátano", proteina: 1.1, carbohidrato: 23, grasa: 0.3, kcal: 89 },
  {
    nombre: "Espinaca",
    proteina: 2.9,
    carbohidrato: 1.1,
    grasa: 0.4,
    kcal: 23,
  },
  { nombre: "Brócoli", proteina: 2.8, carbohidrato: 7, grasa: 0.4, kcal: 34 },
  {
    nombre: "Zanahoria",
    proteina: 0.9,
    carbohidrato: 10,
    grasa: 0.2,
    kcal: 41,
  },
  { nombre: "Tomate", proteina: 0.9, carbohidrato: 3.9, grasa: 0.2, kcal: 18 },
  { nombre: "Queso", proteina: 25, carbohidrato: 1.3, grasa: 33, kcal: 402 },
  { nombre: "Yogur", proteina: 3.5, carbohidrato: 4.7, grasa: 3.3, kcal: 61 },
  {
    nombre: "Frijoles",
    proteina: 8.9,
    carbohidrato: 27,
    grasa: 0.5,
    kcal: 127,
  },
  {
    nombre: "Pechuga de pavo",
    proteina: 24,
    carbohidrato: 0,
    grasa: 1,
    kcal: 104,
  },
  { nombre: "Atún", proteina: 23, carbohidrato: 0, grasa: 1, kcal: 100 },
  { nombre: "Quinoa", proteina: 4.4, carbohidrato: 21, grasa: 1.9, kcal: 120 },
  { nombre: "Camote", proteina: 1.6, carbohidrato: 20, grasa: 0, kcal: 86 },
  { nombre: "Almendra", proteina: 21, carbohidrato: 22, grasa: 49, kcal: 579 },
  { nombre: "Nuez", proteina: 15, carbohidrato: 14, grasa: 65, kcal: 654 },
  { nombre: "Leche", proteina: 3.4, carbohidrato: 5, grasa: 3.3, kcal: 61 },
  { nombre: "Fresa", proteina: 0.7, carbohidrato: 7.7, grasa: 0.3, kcal: 32 },
  { nombre: "Mango", proteina: 0.8, carbohidrato: 15, grasa: 0.4, kcal: 60 },
  { nombre: "Calabaza", proteina: 1, carbohidrato: 7, grasa: 0.1, kcal: 26 },
  { nombre: "Pepino", proteina: 0.7, carbohidrato: 3.6, grasa: 0.1, kcal: 16 },
  {
    nombre: "Espárrago",
    proteina: 2.2,
    carbohidrato: 3.9,
    grasa: 0.1,
    kcal: 20,
  },
  { nombre: "Avena", proteina: 13, carbohidrato: 68, grasa: 7, kcal: 379 },
  { nombre: "Chía", proteina: 17, carbohidrato: 42, grasa: 31, kcal: 486 },
  {
    nombre: "Yogur griego",
    proteina: 10,
    carbohidrato: 3.6,
    grasa: 0.4,
    kcal: 59,
  },
  // Más frutas
  { nombre: "Pera", proteina: 0.4, carbohidrato: 15, grasa: 0.1, kcal: 57 },
  { nombre: "Uva", proteina: 0.7, carbohidrato: 17, grasa: 0.2, kcal: 69 },
  { nombre: "Sandía", proteina: 0.6, carbohidrato: 8, grasa: 0.2, kcal: 30 },
  { nombre: "Melón", proteina: 0.8, carbohidrato: 8, grasa: 0.2, kcal: 34 },
  { nombre: "Piña", proteina: 0.5, carbohidrato: 13, grasa: 0.1, kcal: 50 },
  { nombre: "Durazno", proteina: 0.9, carbohidrato: 10, grasa: 0.3, kcal: 39 },
  { nombre: "Ciruela", proteina: 0.7, carbohidrato: 11, grasa: 0.3, kcal: 46 },
  { nombre: "Papaya", proteina: 0.5, carbohidrato: 11, grasa: 0.3, kcal: 43 },
  { nombre: "Kiwi", proteina: 1.1, carbohidrato: 15, grasa: 0.5, kcal: 61 },
  {
    nombre: "Mandarina",
    proteina: 0.8,
    carbohidrato: 12,
    grasa: 0.2,
    kcal: 53,
  },
  { nombre: "Naranja", proteina: 0.9, carbohidrato: 12, grasa: 0.1, kcal: 47 },
  // Más verduras
  {
    nombre: "Jitomate",
    proteina: 0.9,
    carbohidrato: 3.9,
    grasa: 0.2,
    kcal: 21,
  },
  { nombre: "Cebolla", proteina: 1.1, carbohidrato: 9, grasa: 0.1, kcal: 40 },
  { nombre: "Lechuga", proteina: 1.4, carbohidrato: 2.9, grasa: 0.2, kcal: 15 },
  { nombre: "Coliflor", proteina: 1.9, carbohidrato: 5, grasa: 0.3, kcal: 25 },
  {
    nombre: "Calabacita",
    proteina: 1.2,
    carbohidrato: 3.1,
    grasa: 0.2,
    kcal: 17,
  },
  { nombre: "Betabel", proteina: 1.6, carbohidrato: 10, grasa: 0.2, kcal: 43 },
  {
    nombre: "Champiñón",
    proteina: 3.1,
    carbohidrato: 3.3,
    grasa: 0.3,
    kcal: 22,
  },
  { nombre: "Apio", proteina: 0.7, carbohidrato: 3, grasa: 0.2, kcal: 16 },
  // Más grasas saludables
  { nombre: "Pepitas", proteina: 19, carbohidrato: 15, grasa: 49, kcal: 559 },
  { nombre: "Cacahuate", proteina: 25, carbohidrato: 16, grasa: 49, kcal: 567 },
  { nombre: "Aceituna", proteina: 0.8, carbohidrato: 6, grasa: 11, kcal: 115 },
  {
    nombre: "Semilla de girasol",
    proteina: 21,
    carbohidrato: 20,
    grasa: 51,
    kcal: 584,
  },
  {
    nombre: "Semilla de calabaza",
    proteina: 30,
    carbohidrato: 11,
    grasa: 49,
    kcal: 559,
  },
  { nombre: "Tahini", proteina: 17, carbohidrato: 23, grasa: 53, kcal: 595 },
  {
    nombre: "Mantequilla de maní",
    proteina: 25,
    carbohidrato: 20,
    grasa: 50,
    kcal: 588,
  },
  { nombre: "Coco", proteina: 3.3, carbohidrato: 15, grasa: 33, kcal: 354 },
  { nombre: "Linaza", proteina: 18, carbohidrato: 29, grasa: 42, kcal: 534 },
];

export const RECETAS = [
  {
    nombre: "Ensalada de pollo",
    ingredientes: ["Pollo", "Espinaca", "Tomate", "Aceite de oliva"],
    calorias: 350,
    macros: { proteina: 30, carbohidrato: 10, grasa: 15 },
  },
  {
    nombre: "Bowl de quinoa y pavo",
    ingredientes: ["Pechuga de pavo", "Quinoa", "Brócoli", "Zanahoria"],
    calorias: 420,
    macros: { proteina: 32, carbohidrato: 50, grasa: 8 },
  },
  {
    nombre: "Avena con plátano y nuez",
    ingredientes: ["Avena", "Plátano", "Nuez", "Leche"],
    calorias: 380,
    macros: { proteina: 12, carbohidrato: 60, grasa: 12 },
  },
  {
    nombre: "Tostadas de atún",
    ingredientes: ["Atún", "Papa", "Pepino", "Aguacate"],
    calorias: 340,
    macros: { proteina: 28, carbohidrato: 35, grasa: 8 },
  },
  {
    nombre: "Smoothie de fresa y yogur",
    ingredientes: ["Fresa", "Yogur griego", "Chía", "Leche"],
    calorias: 250,
    macros: { proteina: 15, carbohidrato: 30, grasa: 6 },
  },
  {
    nombre: "Camote al horno con pollo",
    ingredientes: ["Camote", "Pollo", "Espárrago", "Aceite de oliva"],
    calorias: 410,
    macros: { proteina: 27, carbohidrato: 55, grasa: 10 },
  },
  {
    nombre: "Wrap de pavo y queso",
    ingredientes: [
      "Pechuga de pavo",
      "Queso",
      "Espinaca",
      "Tortilla de harina",
    ],
    calorias: 370,
    macros: { proteina: 25, carbohidrato: 40, grasa: 11 },
  },
  {
    nombre: "Ensalada de atún y mango",
    ingredientes: ["Atún", "Mango", "Pepino", "Aceite de oliva"],
    calorias: 320,
    macros: { proteina: 22, carbohidrato: 28, grasa: 9 },
  },
  {
    nombre: "Quinoa con verduras y tofu",
    ingredientes: ["Quinoa", "Tofu", "Calabaza", "Brócoli"],
    calorias: 360,
    macros: { proteina: 18, carbohidrato: 55, grasa: 8 },
  },
  {
    nombre: "Tazón de arroz y res",
    ingredientes: ["Res", "Arroz", "Brócoli", "Zanahoria"],
    calorias: 500,
    macros: { proteina: 35, carbohidrato: 60, grasa: 10 },
  },
  {
    nombre: "Omelette de verduras",
    ingredientes: ["Huevo", "Espinaca", "Tomate", "Queso"],
    calorias: 300,
    macros: { proteina: 20, carbohidrato: 5, grasa: 20 },
  },
  {
    nombre: "Pasta con atún",
    ingredientes: ["Pasta", "Pescado", "Aceite de oliva", "Brócoli"],
    calorias: 450,
    macros: { proteina: 25, carbohidrato: 60, grasa: 12 },
  },
  {
    nombre: "Tacos de frijol",
    ingredientes: ["Frijoles", "Papa", "Aguacate", "Tomate"],
    calorias: 400,
    macros: { proteina: 15, carbohidrato: 65, grasa: 10 },
  },
];
